### ISSUE TITLE
Compatibility with psr/log

### ISSUE THREAD

**Issue by aksld** [Pierre-Lannoy/wp-decalog-sdk#3]
The SDK requires version 1 of psr/log, which is restrictive when using other dependencies that need a more recent version of psr/log.

Would it be possible for the SDK to be compatible with a more recent version? 2 or 3, I don't know exactly.

Thanks again for this tool!

**Comment by Pierre-Lannoy** [comment]
Hello Axel!
Thank you for your kind words :)
Yes, the PSR-3 version is a pain in the ass for many SDK… But I'm working on it to allow users to choose the version that makes more sense for their stack.

**Comment by Pierre-Lannoy** [comment]
Hello !
The SDK, starting from version 5, allows you to choose which version of PSR-3 to use.
